export const CREATE_SPACE = "CREATE_SPACE"
export const GUEST_NUM = "GUEST_NUM"
export const SEND_MESSAGE = "SEND_MESSAGE"
export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE"
export const CHANGE_NAME = "CHANGE_NAME"
export const NEW_MESSAGE = "NEW_MESSAGE"
export const USER_TYPE = "USER_TYPE"
export const COMPLETION = "COMPLETION"
export const NEWUSER = "NEW_USER"
export const CONNECTED = "CONNECTED"
export const NEWQUEUE = "NEWQUEUE"
export const CONNECTING = "CONNECTING"

